/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16 (Ubuntu)
 * Generated at: 2026-07-02 02:22:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class quiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/workspaces/ketu_project/tomcat_local/webapps/samplePro_A_tame/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664453478000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1782957732000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>AI簡易クイズシステム</title>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	font-family: 'Helvetica Neue', Arial, 'Hiragino Kaku Gothic ProN',\n");
      out.write("		Meiryo, sans-serif;\n");
      out.write("	background-color: #f4f6f9;\n");
      out.write("	color: #333;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	max-width: 700px;\n");
      out.write("	margin: 0 auto;\n");
      out.write("	background: #ffffff;\n");
      out.write("	padding: 30px;\n");
      out.write("	border-radius: 8px;\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1, h2 {\n");
      out.write("	text-align: center;\n");
      out.write("	color: #2c3e50;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group {\n");
      out.write("	margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("label {\n");
      out.write("	display: block;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-bottom: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"text\"] {\n");
      out.write("	width: 100%;\n");
      out.write("	padding: 12px;\n");
      out.write("	font-size: 16px;\n");
      out.write("	border: 1px solid #ccc;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button, input[type=\"submit\"] {\n");
      out.write("	background-color: #3498db;\n");
      out.write("	color: white;\n");
      out.write("	border: none;\n");
      out.write("	padding: 12px 20px;\n");
      out.write("	font-size: 16px;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	width: 100%;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button:hover, input[type=\"submit\"]:hover {\n");
      out.write("	background-color: #2980b9;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".question-card {\n");
      out.write("	background: #fdfdfd;\n");
      out.write("	border: 1px solid #eef2f5;\n");
      out.write("	padding: 20px;\n");
      out.write("	margin-bottom: 25px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".question-text {\n");
      out.write("	font-size: 17px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-bottom: 12px;\n");
      out.write("	color: #2c3e50;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".option-label {\n");
      out.write("	display: block;\n");
      out.write("	background: #f8fafc;\n");
      out.write("	border: 1px solid #e2e8f0;\n");
      out.write("	padding: 12px;\n");
      out.write("	margin-bottom: 8px;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	transition: background 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".option-label:hover {\n");
      out.write("	background: #edf2f7;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".option-label input {\n");
      out.write("	margin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".result-card {\n");
      out.write("	border-left: 5px solid #bdc3c7;\n");
      out.write("	padding-left: 15px;\n");
      out.write("	margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".result-card.correct {\n");
      out.write("	border-left-color: #2ecc71;\n");
      out.write("	background-color: #ebfaf0;\n");
      out.write("	padding: 15px;\n");
      out.write("	border-radius: 0 4px 4px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".result-card.incorrect {\n");
      out.write("	border-left-color: #e74c3c;\n");
      out.write("	background-color: #fdf2f2;\n");
      out.write("	padding: 15px;\n");
      out.write("	border-radius: 0 4px 4px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".score-box {\n");
      out.write("	text-align: center;\n");
      out.write("	font-size: 24px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-bottom: 30px;\n");
      out.write("	padding: 15px;\n");
      out.write("	background: #e8f4fc;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	color: #2980b9;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".explanation {\n");
      out.write("	font-size: 14px;\n");
      out.write("	color: #555;\n");
      out.write("	margin-top: 8px;\n");
      out.write("	font-style: italic;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".back-link {\n");
      out.write("	display: block;\n");
      out.write("	text-align: center;\n");
      out.write("	margin-top: 20px;\n");
      out.write("	color: #3498db;\n");
      out.write("	text-decoration: none;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".msgBox.error {\n");
      out.write("	background-color: #fdf2f2;\n");
      out.write("	color: #e74c3c;\n");
      out.write("	padding: 12px;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	margin-bottom: 20px;\n");
      out.write("	border: 1px solid #f8d7da;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div class=\"container\" id=\"quiz-container\">\n");
      out.write("\n");
      out.write("		");
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("		");

        Object stateObj = request.getAttribute("state");
        String state = (stateObj != null) ? (String) stateObj : "input";
        Object quizObj = session.getAttribute("quiz");
        
        if ("input".equals(state)) {
    
      out.write("\n");
      out.write("		<h1>AIクイズジェネレーター</h1>\n");
      out.write("		<p style=\"text-align: center; color: #666; margin-bottom: 30px;\">Gemini\n");
      out.write("			AIがあなたの指定したテーマで瞬時にオリジナルの4択クイズを作成します。</p>\n");
      out.write("\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/QuizServlet\"\n");
      out.write("			method=\"POST\">\n");
      out.write("			<input type=\"hidden\" name=\"action\" value=\"generate\">\n");
      out.write("			<div class=\"form-group\" id=\"input-group\">\n");
      out.write("				<label for=\"topic\">学習したいテーマ、またはお題を入力してください：</label> <input\n");
      out.write("					type=\"text\" id=\"topic\" name=\"topic\"\n");
      out.write("					placeholder=\"例：Java基礎, 日本の戦国時代, 世界のご当地料理\" required>\n");
      out.write("			</div>\n");
      out.write("			<button type=\"submit\" id=\"btn-generate\">クイズを生成する（API同期呼出）</button>\n");
      out.write("		</form>\n");
      out.write("		");

        } else if ("play".equals(state) && quizObj != null) {
            String title = (String) request.getAttribute("quizTitle");
            String description = (String) request.getAttribute("quizDescription");
            List<java.util.Map<String, Object>> questions = (List<java.util.Map<String, Object>>) request.getAttribute("questionsList");
    
      out.write("\n");
      out.write("		<h2>");
      out.print( title );
      out.write("</h2>\n");
      out.write("		<p style=\"color: #666; text-align: center; margin-bottom: 25px;\">");
      out.print( description );
      out.write("</p>\n");
      out.write("\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/QuizServlet\"\n");
      out.write("			method=\"POST\">\n");
      out.write("			<input type=\"hidden\" name=\"action\" value=\"grade\">\n");
      out.write("\n");
      out.write("			");
 
                if (questions != null) {
                    for (int i = 0; i < questions.size(); i++) {
                        java.util.Map<String, Object> q = questions.get(i);
                        String qText = (String) q.get("questionText");
                        List<String> options = (List<String>) q.get("options");
            
      out.write("\n");
      out.write("			<div class=\"question-card\" id=\"q-card-");
      out.print( i );
      out.write("\">\n");
      out.write("				<div class=\"question-text\">\n");
      out.write("					問\n");
      out.write("					");
      out.print( (i + 1) );
      out.write(".\n");
      out.write("					");
      out.print( qText );
      out.write("</div>\n");
      out.write("				<div class=\"options-container\" id=\"options-");
      out.print( i );
      out.write("\">\n");
      out.write("					");
 for (int j = 0; j < options.size(); j++) { 
      out.write("\n");
      out.write("					<label class=\"option-label\" id=\"label-");
      out.print( i );
      out.write('-');
      out.print( j );
      out.write("\"> <input\n");
      out.write("						type=\"radio\" name=\"ans_");
      out.print( i );
      out.write("\" value=\"");
      out.print( j );
      out.write("\" required>\n");
      out.write("						");
      out.print( options.get(j) );
      out.write("\n");
      out.write("					</label>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			");
 
                    }
                } 
            
      out.write("\n");
      out.write("\n");
      out.write("			<button type=\"submit\" id=\"btn-grade\">回答を送信して採点する</button>\n");
      out.write("		</form>\n");
      out.write("		");

        } else if ("result".equals(state)) {
            Integer score = (Integer) request.getAttribute("score");
            Integer total = (Integer) request.getAttribute("total");
            List<java.util.Map<String, Object>> resultsList = (List<java.util.Map<String, Object>>) request.getAttribute("resultsList");
    
      out.write("\n");
      out.write("		<h2>採点結果</h2>\n");
      out.write("		<div class=\"score-box\" id=\"score-display\">\n");
      out.write("			得点:\n");
      out.write("			");
      out.print( score );
      out.write("\n");
      out.write("			/\n");
      out.write("			");
      out.print( total );
      out.write("\n");
      out.write("			問\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		");
 
            if (resultsList != null) {
                for (int i = 0; i < resultsList.size(); i++) {
                    java.util.Map<String, Object> res = resultsList.get(i);
                    String qText = (String) res.get("questionText");
                    List<String> options = (List<String>) res.get("options");
                    int userAns = (Integer) res.get("userAns");
                    int correctAns = (Integer) res.get("correctAns");
                    String exp = (String) res.get("explanation");
                    boolean isCorrect = (userAns == correctAns);
        
      out.write("\n");
      out.write("		<div class=\"question-card ");
      out.print( isCorrect ? "correct" : "incorrect" );
      out.write("\"\n");
      out.write("			id=\"res-card-");
      out.print( i );
      out.write("\">\n");
      out.write("			<div class=\"question-text\" style=\"margin-bottom: 8px;\">\n");
      out.write("				問\n");
      out.write("				");
      out.print( (i + 1) );
      out.write(".\n");
      out.write("				");
      out.print( qText );
      out.write("\n");
      out.write("				<span\n");
      out.write("					style=\"float: right; font-weight: bold; color: ");
      out.print( isCorrect ? "#2ecc71" : "#e74c3c" );
      out.write(";\">\n");
      out.write("					");
      out.print( isCorrect ? "〇 正解" : "× 不正解" );
      out.write("\n");
      out.write("				</span>\n");
      out.write("			</div>\n");
      out.write("			<div style=\"clear: both;\"></div>\n");
      out.write("\n");
      out.write("			<p style=\"margin: 5px 0;\">\n");
      out.write("				あなたの回答: <strong>");
      out.print( userAns >= 0 ? options.get(userAns) : "未回答" );
      out.write("</strong>\n");
      out.write("			</p>\n");
      out.write("			<p style=\"margin: 5px 0; color: #2ecc71;\">\n");
      out.write("				正解: <strong>");
      out.print( options.get(correctAns) );
      out.write("</strong>\n");
      out.write("			</p>\n");
      out.write("\n");
      out.write("			<div class=\"explanation\" id=\"exp-");
      out.print( i );
      out.write("\">\n");
      out.write("				<strong>解説:</strong>\n");
      out.write("				");
      out.print( exp );
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		");
 
                }
            } 
        
      out.write("\n");
      out.write("\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/QuizServlet?action=reset\"\n");
      out.write("			class=\"back-link\" id=\"link-restart\">別のテーマでクイズを遊ぶ</a>\n");
      out.write("		");

        }
    
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /jsp/quiz.jsp(166,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div class=\"msgBox error\">\n");
          out.write("				");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			</div>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /jsp/quiz.jsp(168,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
